let row = document.querySelector(".row");
let col3 = document.querySelector(".col-3");
row.append(col3);
let card = document.querySelector("#card-1");
col3.append(card);
card.style.width = "300px";
card.style.backgroundColor = "white";
let cardImg = document.querySelector("#card-img");
let cardImg2 = document.createElement("img");
cardImg2.src = "michael.png";
cardImg2.style.width = "300px";
cardImg2.style.height = "300px";
cardImg.append(cardImg2);
card.append(cardImg);
let cardContent = document.querySelector("#card-content");
let h2 = document.createElement("h2");
h2.textContent = "Michael";
cardContent.prepend(h2);
h2.style.textAlign = "center";
card.append(cardContent);
let p = document.createElement("p");
p.textContent =
  "Michael works as a programmer at Google. He has been working there for 7 years. Likes gingerbread.";
p.style.padding = "0px 10px 10px 10px";
cardContent.append(p);
